### ISSUE TITLE
sitemapLocation changes

### ISSUE THREAD

**Issue by vvo** [algolia/algolia-sitemap#10]
sitemapLocation.href and sitemapLocation.path are not linked.

*href* is used to determine the full url path of the sub sitemaps in the output and *path* is the output folder where all sitemaps are written locally on disk.

I would go for:

```js
{
  outputFolder, // since it's the output folder of the sitemaps locally
  rootLoc, // since it's used in <loc> inside sitemap
}
```

**Comment by Haroenv** [comment]
`rootLoc` might still be a bit cryptic though, although it is already better than `sitemapLocation.href`. I wonder what the other options could be.

**Comment by vvo** [comment]
Yes "root" is linked to filesystems sometimes or very local.

We could use "location", nothing better atm :D

**Comment by mikaa123** [comment]
what about simply `url` or `href`?

**Comment by mikaa123** [comment]
#19 fixes that, closing
