### ISSUE TITLE
Vulnerability in validator dependency

### ISSUE THREAD

**Issue by WillyReyno** [algolia/algolia-sitemap#222]
Hello! 

The `"validator": "^10.0.0"` dependency in package.json has a vulnerability to  Inefficient Regular Expression Complexity for all versions prior to 13.7.0 
CVE : https://github.com/advisories/GHSA-qgmg-gppg-76g5

Do you have any update planned to fix it?

**Comment by Haroenv** [comment]
This vulnerability wasn't actually possible to be reached in this code, but sure, I updated it. v2.2.2
